name: Go Build and Docker Deploy

on:
  push:
    branches:
      - github-actions-integration    # Adjust branch as needed
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'  # Set your desired Go version

      - name: Build Go binary
        run: |
          go mod download
          go build -o main ./cmd/main.go
          
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # Replace below with your desired image name and tag
          tags: juvination/mapletools:latest
